version: '3'

services:

  php:
    image: ghcr.io/aasaam/vulnerable-application:latest
    restart: unless-stopped
    working_dir: /app/php
    volumes:
      - ./app/php:/app/php:ro
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      SA_PASSWORD: ${SA_PASSWORD}
    networks:
      - app-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 10803:8080
    networks:
      - app-network

  aasaam-web-server:
    image: ghcr.io/aasaam/web-server:latest
    restart: unless-stopped
    volumes:
      - ./addon:/usr/local/openresty/nginx/addon:ro
    ports:
      - 10801:80
      - 10802:443
    networks:
      - app-network

  nginx:
    image: nginx:1
    restart: unless-stopped
    volumes:
      - ./app/php:/app/php:ro
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 10800:8080
    networks:
      - app-network

  mysql:
    image: mysql:5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  postgres:
    image: postgres:9
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: ${SA_PASSWORD}
    networks:
      - app-network

  oracle:
    image: wnameless/oracle-xe-11g-r2
    restart: unless-stopped
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
